//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceTest.CategoriasWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categoria", Namespace="http://schemas.datacontract.org/2004/07/WCFNullPointers.Dominio")]
    [System.SerializableAttribute()]
    public partial class Categoria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CategoriasWS.ICategorias")]
    public interface ICategorias {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategorias/CrearCategoria", ReplyAction="http://tempuri.org/ICategorias/CrearCategoriaResponse")]
        string CrearCategoria(WCFServiceTest.CategoriasWS.Categoria categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategorias/CrearCategoria", ReplyAction="http://tempuri.org/ICategorias/CrearCategoriaResponse")]
        System.Threading.Tasks.Task<string> CrearCategoriaAsync(WCFServiceTest.CategoriasWS.Categoria categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategorias/ObtenerCategoria", ReplyAction="http://tempuri.org/ICategorias/ObtenerCategoriaResponse")]
        string ObtenerCategoria(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategorias/ObtenerCategoria", ReplyAction="http://tempuri.org/ICategorias/ObtenerCategoriaResponse")]
        System.Threading.Tasks.Task<string> ObtenerCategoriaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategorias/ModificarCategoria", ReplyAction="http://tempuri.org/ICategorias/ModificarCategoriaResponse")]
        string ModificarCategoria(WCFServiceTest.CategoriasWS.Categoria categoriaAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategorias/ModificarCategoria", ReplyAction="http://tempuri.org/ICategorias/ModificarCategoriaResponse")]
        System.Threading.Tasks.Task<string> ModificarCategoriaAsync(WCFServiceTest.CategoriasWS.Categoria categoriaAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategorias/EliminarCategoria", ReplyAction="http://tempuri.org/ICategorias/EliminarCategoriaResponse")]
        void EliminarCategoria(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategorias/EliminarCategoria", ReplyAction="http://tempuri.org/ICategorias/EliminarCategoriaResponse")]
        System.Threading.Tasks.Task EliminarCategoriaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategorias/ListarCategoria", ReplyAction="http://tempuri.org/ICategorias/ListarCategoriaResponse")]
        WCFServiceTest.CategoriasWS.Categoria[] ListarCategoria();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategorias/ListarCategoria", ReplyAction="http://tempuri.org/ICategorias/ListarCategoriaResponse")]
        System.Threading.Tasks.Task<WCFServiceTest.CategoriasWS.Categoria[]> ListarCategoriaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICategoriasChannel : WCFServiceTest.CategoriasWS.ICategorias, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategoriasClient : System.ServiceModel.ClientBase<WCFServiceTest.CategoriasWS.ICategorias>, WCFServiceTest.CategoriasWS.ICategorias {
        
        public CategoriasClient() {
        }
        
        public CategoriasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategoriasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CrearCategoria(WCFServiceTest.CategoriasWS.Categoria categoria) {
            return base.Channel.CrearCategoria(categoria);
        }
        
        public System.Threading.Tasks.Task<string> CrearCategoriaAsync(WCFServiceTest.CategoriasWS.Categoria categoria) {
            return base.Channel.CrearCategoriaAsync(categoria);
        }
        
        public string ObtenerCategoria(int id) {
            return base.Channel.ObtenerCategoria(id);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerCategoriaAsync(int id) {
            return base.Channel.ObtenerCategoriaAsync(id);
        }
        
        public string ModificarCategoria(WCFServiceTest.CategoriasWS.Categoria categoriaAModificar) {
            return base.Channel.ModificarCategoria(categoriaAModificar);
        }
        
        public System.Threading.Tasks.Task<string> ModificarCategoriaAsync(WCFServiceTest.CategoriasWS.Categoria categoriaAModificar) {
            return base.Channel.ModificarCategoriaAsync(categoriaAModificar);
        }
        
        public void EliminarCategoria(int id) {
            base.Channel.EliminarCategoria(id);
        }
        
        public System.Threading.Tasks.Task EliminarCategoriaAsync(int id) {
            return base.Channel.EliminarCategoriaAsync(id);
        }
        
        public WCFServiceTest.CategoriasWS.Categoria[] ListarCategoria() {
            return base.Channel.ListarCategoria();
        }
        
        public System.Threading.Tasks.Task<WCFServiceTest.CategoriasWS.Categoria[]> ListarCategoriaAsync() {
            return base.Channel.ListarCategoriaAsync();
        }
    }
}
