//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceTest.UsuariosWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/WCFNullPointers.Dominio")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasena {
            get {
                return this.ContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasenaField, value) != true)) {
                    this.ContrasenaField = value;
                    this.RaisePropertyChanged("Contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni {
            get {
                return this.DniField;
            }
            set {
                if ((object.ReferenceEquals(this.DniField, value) != true)) {
                    this.DniField = value;
                    this.RaisePropertyChanged("Dni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsuariosWS.IUsuarios")]
    public interface IUsuarios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/CrearUsuario", ReplyAction="http://tempuri.org/IUsuarios/CrearUsuarioResponse")]
        string CrearUsuario(WCFServiceTest.UsuariosWS.Usuario usuarioACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/CrearUsuario", ReplyAction="http://tempuri.org/IUsuarios/CrearUsuarioResponse")]
        System.Threading.Tasks.Task<string> CrearUsuarioAsync(WCFServiceTest.UsuariosWS.Usuario usuarioACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ObtenerUsuario", ReplyAction="http://tempuri.org/IUsuarios/ObtenerUsuarioResponse")]
        string ObtenerUsuario(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ObtenerUsuario", ReplyAction="http://tempuri.org/IUsuarios/ObtenerUsuarioResponse")]
        System.Threading.Tasks.Task<string> ObtenerUsuarioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/LoginUsuario", ReplyAction="http://tempuri.org/IUsuarios/LoginUsuarioResponse")]
        string LoginUsuario(string codigo, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/LoginUsuario", ReplyAction="http://tempuri.org/IUsuarios/LoginUsuarioResponse")]
        System.Threading.Tasks.Task<string> LoginUsuarioAsync(string codigo, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ModificarUsuario", ReplyAction="http://tempuri.org/IUsuarios/ModificarUsuarioResponse")]
        string ModificarUsuario(WCFServiceTest.UsuariosWS.Usuario usuarioAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ModificarUsuario", ReplyAction="http://tempuri.org/IUsuarios/ModificarUsuarioResponse")]
        System.Threading.Tasks.Task<string> ModificarUsuarioAsync(WCFServiceTest.UsuariosWS.Usuario usuarioAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/EliminarUsuario", ReplyAction="http://tempuri.org/IUsuarios/EliminarUsuarioResponse")]
        void EliminarUsuario(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/EliminarUsuario", ReplyAction="http://tempuri.org/IUsuarios/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task EliminarUsuarioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ListarUsuarios", ReplyAction="http://tempuri.org/IUsuarios/ListarUsuariosResponse")]
        WCFServiceTest.UsuariosWS.Usuario[] ListarUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ListarUsuarios", ReplyAction="http://tempuri.org/IUsuarios/ListarUsuariosResponse")]
        System.Threading.Tasks.Task<WCFServiceTest.UsuariosWS.Usuario[]> ListarUsuariosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuariosChannel : WCFServiceTest.UsuariosWS.IUsuarios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuariosClient : System.ServiceModel.ClientBase<WCFServiceTest.UsuariosWS.IUsuarios>, WCFServiceTest.UsuariosWS.IUsuarios {
        
        public UsuariosClient() {
        }
        
        public UsuariosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuariosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CrearUsuario(WCFServiceTest.UsuariosWS.Usuario usuarioACrear) {
            return base.Channel.CrearUsuario(usuarioACrear);
        }
        
        public System.Threading.Tasks.Task<string> CrearUsuarioAsync(WCFServiceTest.UsuariosWS.Usuario usuarioACrear) {
            return base.Channel.CrearUsuarioAsync(usuarioACrear);
        }
        
        public string ObtenerUsuario(int id) {
            return base.Channel.ObtenerUsuario(id);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerUsuarioAsync(int id) {
            return base.Channel.ObtenerUsuarioAsync(id);
        }
        
        public string LoginUsuario(string codigo, string contrasena) {
            return base.Channel.LoginUsuario(codigo, contrasena);
        }
        
        public System.Threading.Tasks.Task<string> LoginUsuarioAsync(string codigo, string contrasena) {
            return base.Channel.LoginUsuarioAsync(codigo, contrasena);
        }
        
        public string ModificarUsuario(WCFServiceTest.UsuariosWS.Usuario usuarioAModificar) {
            return base.Channel.ModificarUsuario(usuarioAModificar);
        }
        
        public System.Threading.Tasks.Task<string> ModificarUsuarioAsync(WCFServiceTest.UsuariosWS.Usuario usuarioAModificar) {
            return base.Channel.ModificarUsuarioAsync(usuarioAModificar);
        }
        
        public void EliminarUsuario(int id) {
            base.Channel.EliminarUsuario(id);
        }
        
        public System.Threading.Tasks.Task EliminarUsuarioAsync(int id) {
            return base.Channel.EliminarUsuarioAsync(id);
        }
        
        public WCFServiceTest.UsuariosWS.Usuario[] ListarUsuarios() {
            return base.Channel.ListarUsuarios();
        }
        
        public System.Threading.Tasks.Task<WCFServiceTest.UsuariosWS.Usuario[]> ListarUsuariosAsync() {
            return base.Channel.ListarUsuariosAsync();
        }
    }
}
