//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceTest.ProductosWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/WCFNullPointers.Dominio")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoriaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DescuentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PresentacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoriaId {
            get {
                return this.CategoriaIdField;
            }
            set {
                if ((this.CategoriaIdField.Equals(value) != true)) {
                    this.CategoriaIdField = value;
                    this.RaisePropertyChanged("CategoriaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Descuento {
            get {
                return this.DescuentoField;
            }
            set {
                if ((this.DescuentoField.Equals(value) != true)) {
                    this.DescuentoField = value;
                    this.RaisePropertyChanged("Descuento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Presentacion {
            get {
                return this.PresentacionField;
            }
            set {
                if ((object.ReferenceEquals(this.PresentacionField, value) != true)) {
                    this.PresentacionField = value;
                    this.RaisePropertyChanged("Presentacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductosWS.IProductos")]
    public interface IProductos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/CrearProducto", ReplyAction="http://tempuri.org/IProductos/CrearProductoResponse")]
        string CrearProducto(WCFServiceTest.ProductosWS.Producto productos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/CrearProducto", ReplyAction="http://tempuri.org/IProductos/CrearProductoResponse")]
        System.Threading.Tasks.Task<string> CrearProductoAsync(WCFServiceTest.ProductosWS.Producto productos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/ObtenerProducto", ReplyAction="http://tempuri.org/IProductos/ObtenerProductoResponse")]
        string ObtenerProducto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/ObtenerProducto", ReplyAction="http://tempuri.org/IProductos/ObtenerProductoResponse")]
        System.Threading.Tasks.Task<string> ObtenerProductoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/ModificarProducto", ReplyAction="http://tempuri.org/IProductos/ModificarProductoResponse")]
        string ModificarProducto(WCFServiceTest.ProductosWS.Producto productos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/ModificarProducto", ReplyAction="http://tempuri.org/IProductos/ModificarProductoResponse")]
        System.Threading.Tasks.Task<string> ModificarProductoAsync(WCFServiceTest.ProductosWS.Producto productos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/EliminarProducto", ReplyAction="http://tempuri.org/IProductos/EliminarProductoResponse")]
        void EliminarProducto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/EliminarProducto", ReplyAction="http://tempuri.org/IProductos/EliminarProductoResponse")]
        System.Threading.Tasks.Task EliminarProductoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/ListarProductos", ReplyAction="http://tempuri.org/IProductos/ListarProductosResponse")]
        WCFServiceTest.ProductosWS.Producto[] ListarProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/ListarProductos", ReplyAction="http://tempuri.org/IProductos/ListarProductosResponse")]
        System.Threading.Tasks.Task<WCFServiceTest.ProductosWS.Producto[]> ListarProductosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductosChannel : WCFServiceTest.ProductosWS.IProductos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductosClient : System.ServiceModel.ClientBase<WCFServiceTest.ProductosWS.IProductos>, WCFServiceTest.ProductosWS.IProductos {
        
        public ProductosClient() {
        }
        
        public ProductosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CrearProducto(WCFServiceTest.ProductosWS.Producto productos) {
            return base.Channel.CrearProducto(productos);
        }
        
        public System.Threading.Tasks.Task<string> CrearProductoAsync(WCFServiceTest.ProductosWS.Producto productos) {
            return base.Channel.CrearProductoAsync(productos);
        }
        
        public string ObtenerProducto(int id) {
            return base.Channel.ObtenerProducto(id);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerProductoAsync(int id) {
            return base.Channel.ObtenerProductoAsync(id);
        }
        
        public string ModificarProducto(WCFServiceTest.ProductosWS.Producto productos) {
            return base.Channel.ModificarProducto(productos);
        }
        
        public System.Threading.Tasks.Task<string> ModificarProductoAsync(WCFServiceTest.ProductosWS.Producto productos) {
            return base.Channel.ModificarProductoAsync(productos);
        }
        
        public void EliminarProducto(int id) {
            base.Channel.EliminarProducto(id);
        }
        
        public System.Threading.Tasks.Task EliminarProductoAsync(int id) {
            return base.Channel.EliminarProductoAsync(id);
        }
        
        public WCFServiceTest.ProductosWS.Producto[] ListarProductos() {
            return base.Channel.ListarProductos();
        }
        
        public System.Threading.Tasks.Task<WCFServiceTest.ProductosWS.Producto[]> ListarProductosAsync() {
            return base.Channel.ListarProductosAsync();
        }
    }
}
